version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlai-consumer
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0
    network_mode: bridge
